/*
      Title:  SQL CODE FOR CREATING THE DATABASE
 */

/*  to create the database   */
CREATE DATABASE StoutPages;

CREATE TABLE ACCOUNT(
  ACC_UNAME VARCHAR(25) NOT NULL UNIQUE PRIMARY KEY,   /*  username is primary key  */
  ACC_FNAME VARCHAR(25) NOT NULL,
  ACC_LNAME VARCHAR(25) NOT NULL,
  ACC_PASS CHAR(32) NOT NULL,
  ACC_BEER VARCHAR(25)
);


CREATE TABLE STATS(
  STAT_NAME VARCHAR(20) NOT NULL,
  STAT_VOTES INT(20)
);

/*    insert some data in these fields    */

INSERT INTO ACCOUNT (ACC_UNAME, ACC_FNAME, ACC_LNAME, ACC_PASS, ACC_BEER)
            VALUES ( 'nmerck1', 'Nathaniel', 'Merck', 'foo1234', 'PBR' );

INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Guinness', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Blue Moon', 5 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Samuel Adams', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Heineken', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Corona', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Stella Artois', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Budweiser', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Sierra Nevada', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Yuengling', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Hoegaarden', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Pilsner Urquell', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Pabst Blue Ribbon', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Coors Light', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Stone Pale Ale', 4 );
INSERT INTO STATS (STAT_NAME, STAT_VOTES) VALUES ( 'Rolling Rock', 3 );

/*    // Extra code: //

    ACC_EMAIL VARCHAR(100) NOT NULL,

*/