

/*  to create the database   */
CREATE DATABASE StoutPages;

/*  to create account table  */
CREATE TABLE ACCOUNT(
  ACC_UNAME VARCHAR(25) NOT NULL UNIQUE PRIMARY KEY,   /*  username is primary key  */
  ACC_FNAME VARCHAR(25) NOT NULL,
  ACC_LNAME VARCHAR(25) NOT NULL,
  ACC_PASS CHAR(32) NOT NULL,
  ACC_BEER VARCHAR(25)
);

/*  to create the statistics table  */
CREATE TABLE STATS(
  STAT_GUINNESS INT(20),
  STAT_BLUEMOON INT(20),
  STAT_SAMUELADAMS INT(20),
  STAT_HEINEKEN INT(20),
  STAT_CORONA INT(20),
  STAT_STELLA INT(20),
  STAT_BUDWEISER INT(20),
  STAT_SIERRA INT(20),
  STAT_YUENGLING INT(20),
  STAT_HOEGAARDEN INT(20),
  STAT_PILSNER INT(20),
  STAT_PBR INT(20),
  STAT_COORS INT(20),
  STAT_STONE INT(20),
  STAT_ROCK INT(20)
);

/*    // Extra code: //

    ACC_EMAIL VARCHAR(100) NOT NULL,

*/